# Generated by Django 3.1.1 on 2020-09-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('faculty', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to=None)),
                ('age', models.IntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Groups.group')),
            ],
        ),
    ]
