# Generated by Django 3.1.1 on 2020-09-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
