# Generated by Django 3.1.1 on 2020-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20200902_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
