# Generated by Django 3.1.1 on 2020-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_auto_20200903_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=1111, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=1111, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
