# Generated by Django 3.1.1 on 2020-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_auto_20200903_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=None),
        ),
    ]
