# Generated by Django 3.1.1 on 2020-09-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0006_auto_20200905_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
