# Generated by Django 3.1.1 on 2020-09-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0008_auto_20200905_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=1111, upload_to=''),
            preserve_default=False,
        ),
    ]
